export const websites = [
  "https://www.google.com",
  "https://www.facebook.com",
  "https://www.amazon.com",
  "https://www.reddit.com",
  "https://www.twitter.com",
  "https://www.linkedin.com",
  "https://www.youtube.com",
  "https://www.instagram.com",
  "https://www.netflix.com",
  "https://www.wikipedia.org",
  "https://www.apple.com",
  "https://www.microsoft.com",
  "https://www.nytimes.com",
  "https://www.bbc.com",
  "https://www.cnn.com",
  "https://www.etsy.com",
  "https://www.tesla.com",
  "https://www.airbnb.com",
  "https://www.paypal.com",
  "https://www.shopify.com",
  "https://www.adobe.com",
  "https://www.quora.com",
  "https://www.stackoverflow.com",
  "https://www.medium.com",
  "https://www.twitch.tv",
  "https://www.pinterest.com",
  "https://www.dropbox.com",
  "https://www.figma.com",
  "https://www.soundcloud.com",
  "https://www.cloudflare.com",
];

export const devices = [
  "mobile",
  "tablet",
  "console",
  "smarttv",
  "wearable",
  "xr",
  "embedded",
];

export const osNames = [
  "Windows",
  "Windows Phone",
  "Mac OS",
  "iOS",
  "Linux",
  "Ubuntu",
  "Debian",
  "Fedora",
  "Arch",
  "CentOS",
  "Red Hat",
  "Android",
  "Chrome OS",
  "UNIX",
  "FreeBSD",
  "OpenBSD",
  "NetBSD",
  "BlackBerry",
  "Symbian",
  "MeeGo",
  "Tizen",
  "Sailfish",
  "WebOS",
];

export const browserNames = [
  "Chrome",
  "Firefox",
  "Safari",
  "Edge",
  "Opera",
  "IE", // Internet Explorer (Older versions)
  "Brave",
  "Vivaldi",
  "Samsung Internet",
  "UC Browser",
  "Yandex Browser",
  "QQ Browser",
  "Baidu Browser",
  "Puffin",
  "Maxthon",
  "Sleipnir",
  "Seamonkey",
  "Epiphany",
];
